const sampleData = {
  products: [
    {
      name: "Polo Sporting Stretch Shirt",
      slug: "polo-sporting-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Classic Polo style with modern comfort",
      images: [
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109409/p4-2_hvto7m.jpg",
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109408/p4-1_ogjmae.jpg",
      ],
      price: 59.99,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner:
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109381/banner-1_clpzw7.jpg",
    },
    {
      name: "Brooks Brothers Long Sleeved Shirt",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "Men's Dress Shirts",
      description: "Timeless style and premium comfort",
      images: [
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109413/p5-2_m4vble.jpg",
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109411/p5-1_id6wg9.jpg",
      ],
      price: 85.9,
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner:
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109383/banner-2_dkpoht.jpg",
    },
    {
      name: "Tommy Hilfiger Classic Fit Dress Shirt",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "Men's Dress Shirts",
      description: "A perfect blend of sophistication and comfort",
      images: [
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109407/p3-2_kew4vn.jpg",
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109405/p2-2_mh3fdz.jpg",
      ],
      price: 99.95,
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Calvin Klein Slim Fit Stretch Shirt",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Streamlined design with flexible stretch fabric",
      images: [
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109405/p3-1_pbui2f.jpg",
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109404/p2-1_lseb3t.jpg",
      ],
      price: 39.95,
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Ralph Lauren Oxford Shirt",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "Men's Dress Shirts",
      description: "Iconic Polo design with refined oxford fabric",
      images: [
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109400/p1-1_dci8sd.webp",
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109399/p1-2_ifsbvk.webp",
      ],
      price: 79.99,
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Classic Pink Hoodie",
      slug: "polo-classic-pink-hoodie",
      category: "Men's Sweatshirts",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109402/p6-2_gxstjp.webp",
        "https://res.cloudinary.com/dckzwvjj1/image/upload/v1763109401/p6-1_v1k3pe.webp",
      ],
      price: 99.99,
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
